version: '3'

services:
  dev-server:
    image: node:18
    restart: always
    ports:
      - 5173:5173
    command: bash -c "npm install && npm run dev"
    working_dir: /src/
    volumes:
      - .:/src:delegated